Uygulmaya button1 adında yeni buton ekledim.
freebelion/BTS206-2021 pull request #1
Opened 2021-02-15 21:04 UTC by yceomer

2021-02-16 06:52 UTC, freebelion commented
Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık mı, yani
her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?

16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com> şunu
yazdı:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/freebelion/BTS206-2021/pull/1
> Commit Summary
>
>    - Uygulmaya button1 adında yeni buton ekledim.
>
> File Changes
>
>    - *M* Ders1_Ornek/AnaPencere.Designer.cs
>    <https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4>
>    (112)
>
> Patch Links:
>
>    - https://github.com/freebelion/BTS206-2021/pull/1.patch
>    - https://github.com/freebelion/BTS206-2021/pull/1.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA>
> .
>

2021-02-16 07:07 UTC, yceomer commented
Hocam merhaba,

Proje size ait olduğu için size her geliştirme yapan arkadaşın branchi
gelecek ve onayınızı isteyecektir.
Classrooma attığınız proje herkese açık oluyor zaten.
Yani her türlü size onay mesajı gelecektir.

16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <notifications@github.com> şunu
yazdı:

> Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık mı, yani
> her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
>
> 16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com> şunu
> yazdı:
>
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/freebelion/BTS206-2021/pull/1
> > Commit Summary
> >
> > - Uygulmaya button1 adında yeni buton ekledim.
> >
> > File Changes
> >
> > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > <
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> >
> > (112)
> >
> > Patch Links:
> >
> > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1>, or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA>
> .
>

2021-02-16 07:20 UTC, freebelion commented
İşte ben de bu adımları açıklayan bir eğitim sayfası istiyorum. Varsa
bilgili birisi, pazarlık yapalım.

16 Şub 2021 Sal 10:07 tarihinde yceomer <notifications@github.com> şunu
yazdı:

> Hocam merhaba,
>
> Proje size ait olduğu için size her geliştirme yapan arkadaşın branchi
> gelecek ve onayınızı isteyecektir.
> Classrooma attığınız proje herkese açık oluyor zaten.
> Yani her türlü size onay mesajı gelecektir.
>
> 16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <notifications@github.com>
> şunu
> yazdı:
>
> > Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık mı,
> yani
> > her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
> >
> > 16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com> şunu
> > yazdı:
> >
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/freebelion/BTS206-2021/pull/1
> > > Commit Summary
> > >
> > > - Uygulmaya button1 adında yeni buton ekledim.
> > >
> > > File Changes
> > >
> > > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > > <
> >
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> > >
> > > (112)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/freebelion/BTS206-2021/pull/1>, or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779635262>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGBRPEFOCCWXCKVO5H2FQGTS7IKUFANCNFSM4XVJ3MSA>
> .
>

2021-02-16 07:23 UTC, yceomer commented
Hocam Classrooma gerekli tüm adımları içeren ekran görüntülerini paylaştım.

16 Şub 2021 Sal 10:20 tarihinde Hürol Aslan <notifications@github.com> şunu
yazdı:

> İşte ben de bu adımları açıklayan bir eğitim sayfası istiyorum. Varsa
> bilgili birisi, pazarlık yapalım.
>
> 16 Şub 2021 Sal 10:07 tarihinde yceomer <notifications@github.com> şunu
> yazdı:
>
> > Hocam merhaba,
> >
> > Proje size ait olduğu için size her geliştirme yapan arkadaşın branchi
> > gelecek ve onayınızı isteyecektir.
> > Classrooma attığınız proje herkese açık oluyor zaten.
> > Yani her türlü size onay mesajı gelecektir.
> >
> > 16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <notifications@github.com>
> > şunu
> > yazdı:
> >
> > > Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık mı,
> > yani
> > > her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
> > >
> > > 16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com>
> şunu
> > > yazdı:
> > >
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/freebelion/BTS206-2021/pull/1
> > > > Commit Summary
> > > >
> > > > - Uygulmaya button1 adında yeni buton ekledim.
> > > >
> > > > File Changes
> > > >
> > > > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > > > <
> > >
> >
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> > > >
> > > > (112)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > > > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/freebelion/BTS206-2021/pull/1>, or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779635262
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AGBRPEFOCCWXCKVO5H2FQGTS7IKUFANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779640748>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAPDLMF27HBH6E66EVVU73S7IMFHANCNFSM4XVJ3MSA>
> .
>

2021-02-16 09:29 UTC, freebelion commented
Sayfa yapacaktınız. Bedava paylaşımdan not alamazsınız :-)

16 Şub 2021 Sal 10:23 tarihinde yceomer <notifications@github.com> şunu
yazdı:

> Hocam Classrooma gerekli tüm adımları içeren ekran görüntülerini paylaştım.
>
> 16 Şub 2021 Sal 10:20 tarihinde Hürol Aslan <notifications@github.com>
> şunu
> yazdı:
>
> > İşte ben de bu adımları açıklayan bir eğitim sayfası istiyorum. Varsa
> > bilgili birisi, pazarlık yapalım.
> >
> > 16 Şub 2021 Sal 10:07 tarihinde yceomer <notifications@github.com> şunu
> > yazdı:
> >
> > > Hocam merhaba,
> > >
> > > Proje size ait olduğu için size her geliştirme yapan arkadaşın branchi
> > > gelecek ve onayınızı isteyecektir.
> > > Classrooma attığınız proje herkese açık oluyor zaten.
> > > Yani her türlü size onay mesajı gelecektir.
> > >
> > > 16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <notifications@github.com>
> > > şunu
> > > yazdı:
> > >
> > > > Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık
> mı,
> > > yani
> > > > her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
> > > >
> > > > 16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com>
> > şunu
> > > > yazdı:
> > > >
> > > > > ------------------------------
> > > > > You can view, comment on, or merge this pull request online at:
> > > > >
> > > > > https://github.com/freebelion/BTS206-2021/pull/1
> > > > > Commit Summary
> > > > >
> > > > > - Uygulmaya button1 adında yeni buton ekledim.
> > > > >
> > > > > File Changes
> > > > >
> > > > > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > > > > <
> > > >
> > >
> >
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> > > > >
> > > > > (112)
> > > > >
> > > > > Patch Links:
> > > > >
> > > > > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > > > > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> > > > >
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/freebelion/BTS206-2021/pull/1>, or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783
> > > >,
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779635262
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEFOCCWXCKVO5H2FQGTS7IKUFANCNFSM4XVJ3MSA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779640748
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ANAPDLMF27HBH6E66EVVU73S7IMFHANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779641950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGBRPEARVO7JPPKUZKSOJ3DS7IMQHANCNFSM4XVJ3MSA>
> .
>

2021-02-16 09:38 UTC, yceomer commented
Bloğumda paylaşabilirim hocam :)

16 Şub 2021 Sal 12:29 tarihinde Hürol Aslan <notifications@github.com> şunu
yazdı:

> Sayfa yapacaktınız. Bedava paylaşımdan not alamazsınız :-)
>
> 16 Şub 2021 Sal 10:23 tarihinde yceomer <notifications@github.com> şunu
> yazdı:
>
> > Hocam Classrooma gerekli tüm adımları içeren ekran görüntülerini
> paylaştım.
> >
> > 16 Şub 2021 Sal 10:20 tarihinde Hürol Aslan <notifications@github.com>
> > şunu
> > yazdı:
> >
> > > İşte ben de bu adımları açıklayan bir eğitim sayfası istiyorum. Varsa
> > > bilgili birisi, pazarlık yapalım.
> > >
> > > 16 Şub 2021 Sal 10:07 tarihinde yceomer <notifications@github.com>
> şunu
> > > yazdı:
> > >
> > > > Hocam merhaba,
> > > >
> > > > Proje size ait olduğu için size her geliştirme yapan arkadaşın
> branchi
> > > > gelecek ve onayınızı isteyecektir.
> > > > Classrooma attığınız proje herkese açık oluyor zaten.
> > > > Yani her türlü size onay mesajı gelecektir.
> > > >
> > > > 16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <
> notifications@github.com>
> > > > şunu
> > > > yazdı:
> > > >
> > > > > Proje herkese görünür olsun istemiştim, ama ayrıca herkese de açık
> > mı,
> > > > yani
> > > > > her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
> > > > >
> > > > > 16 Şub 2021 Sal 00:05 tarihinde yceomer <notifications@github.com>
> > > şunu
> > > > > yazdı:
> > > > >
> > > > > > ------------------------------
> > > > > > You can view, comment on, or merge this pull request online at:
> > > > > >
> > > > > > https://github.com/freebelion/BTS206-2021/pull/1
> > > > > > Commit Summary
> > > > > >
> > > > > > - Uygulmaya button1 adında yeni buton ekledim.
> > > > > >
> > > > > > File Changes
> > > > > >
> > > > > > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> > > > > >
> > > > > > (112)
> > > > > >
> > > > > > Patch Links:
> > > > > >
> > > > > > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > > > > > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you are subscribed to this thread.
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <https://github.com/freebelion/BTS206-2021/pull/1>, or
> unsubscribe
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> > > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > >
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783
> > > > >,
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779635262
> > > >,
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEFOCCWXCKVO5H2FQGTS7IKUFANCNFSM4XVJ3MSA
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779640748
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLMF27HBH6E66EVVU73S7IMFHANCNFSM4XVJ3MSA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779641950
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AGBRPEARVO7JPPKUZKSOJ3DS7IMQHANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779704801>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAPDLMRST5GNGYXQQ74QSDS7I3HXANCNFSM4XVJ3MSA>
> .
>

2021-02-16 09:39 UTC, freebelion requested changes
Ne işe yarayacağını anlamadığım düğmeye bari anlamlı bir ad koysaydınız :-<

2021-02-16 09:43 UTC, yceomer commented
Hocam sadece arkadaşların anlaması için toolbox kullanarak bir buton
ekledim. İşlevi yok sadece görüntü :|

16 Şub 2021 Sal 12:39 tarihinde Hürol Aslan <notifications@github.com> şunu
yazdı:

> *@freebelion* requested changes on this pull request.
>
> Ne işe yarayacağını anlamadığım düğmeye bari anlamlı bir ad koysaydınız :-<
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#pullrequestreview-591043791>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAPDLOW6CNEVGTOTAWXZIDS7I4MRANCNFSM4XVJ3MSA>
> .
>

2021-02-16 09:45 UTC, freebelion commented
İyisi mi bir ara canlı ders yapın, ben de öğreneyim.
Google Sites eklemek için bir de html sayfası oluşturun.
Ara sınav ve final yerine sayarım.
Ama benim belli nasıl onaylayacağımı, değişiklikleri nasıl birleştireceğimi
de öğrenmeliyim.

16 Şub 2021 Sal 12:38 tarihinde yceomer <notifications@github.com> şunu
yazdı:

> Bloğumda paylaşabilirim hocam :)
>
> 16 Şub 2021 Sal 12:29 tarihinde Hürol Aslan <notifications@github.com>
> şunu
> yazdı:
>
> > Sayfa yapacaktınız. Bedava paylaşımdan not alamazsınız :-)
> >
> > 16 Şub 2021 Sal 10:23 tarihinde yceomer <notifications@github.com> şunu
> > yazdı:
> >
> > > Hocam Classrooma gerekli tüm adımları içeren ekran görüntülerini
> > paylaştım.
> > >
> > > 16 Şub 2021 Sal 10:20 tarihinde Hürol Aslan <notifications@github.com>
> > > şunu
> > > yazdı:
> > >
> > > > İşte ben de bu adımları açıklayan bir eğitim sayfası istiyorum. Varsa
> > > > bilgili birisi, pazarlık yapalım.
> > > >
> > > > 16 Şub 2021 Sal 10:07 tarihinde yceomer <notifications@github.com>
> > şunu
> > > > yazdı:
> > > >
> > > > > Hocam merhaba,
> > > > >
> > > > > Proje size ait olduğu için size her geliştirme yapan arkadaşın
> > branchi
> > > > > gelecek ve onayınızı isteyecektir.
> > > > > Classrooma attığınız proje herkese açık oluyor zaten.
> > > > > Yani her türlü size onay mesajı gelecektir.
> > > > >
> > > > > 16 Şub 2021 Sal 09:52 tarihinde Hürol Aslan <
> > notifications@github.com>
> > > > > şunu
> > > > > yazdı:
> > > > >
> > > > > > Proje herkese görünür olsun istemiştim, ama ayrıca herkese de
> açık
> > > mı,
> > > > > yani
> > > > > > her isteyen katılma talebi göndermeden kod ekleyebiliyor mu?
> > > > > >
> > > > > > 16 Şub 2021 Sal 00:05 tarihinde yceomer <
> notifications@github.com>
> > > > şunu
> > > > > > yazdı:
> > > > > >
> > > > > > > ------------------------------
> > > > > > > You can view, comment on, or merge this pull request online at:
> > > > > > >
> > > > > > > https://github.com/freebelion/BTS206-2021/pull/1
> > > > > > > Commit Summary
> > > > > > >
> > > > > > > - Uygulmaya button1 adında yeni buton ekledim.
> > > > > > >
> > > > > > > File Changes
> > > > > > >
> > > > > > > - *M* Ders1_Ornek/AnaPencere.Designer.cs
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/freebelion/BTS206-2021/pull/1/files#diff-a3384dcf3ac58d2025c24dab7a501f1c8e223fdd8c4562889378302dd34eb7b4
> > > > > > >
> > > > > > > (112)
> > > > > > >
> > > > > > > Patch Links:
> > > > > > >
> > > > > > > - https://github.com/freebelion/BTS206-2021/pull/1.patch
> > > > > > > - https://github.com/freebelion/BTS206-2021/pull/1.diff
> > > > > > >
> > > > > > > —
> > > > > > > You are receiving this because you are subscribed to this
> thread.
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <https://github.com/freebelion/BTS206-2021/pull/1>, or
> > unsubscribe
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEGOB3LHN7C5NCPLFMTS7GEANANCNFSM4XVJ3MSA
> > > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you authored the thread.
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> > > >
> > https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779627783
> > > > > >,
> > > > > > or unsubscribe
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLODTPDOWFK6CDSV2DLS7II2TANCNFSM4XVJ3MSA
> > > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you commented.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > >
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779635262
> > > > >,
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEFOCCWXCKVO5H2FQGTS7IKUFANCNFSM4XVJ3MSA
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779640748
> > > >,
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/ANAPDLMF27HBH6E66EVVU73S7IMFHANCNFSM4XVJ3MSA
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779641950
> > >,
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/AGBRPEARVO7JPPKUZKSOJ3DS7IMQHANCNFSM4XVJ3MSA
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779704801
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ANAPDLMRST5GNGYXQQ74QSDS7I3HXANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779710622>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGBRPEAN6T3DCAJDRFBKNQ3S7I4KPANCNFSM4XVJ3MSA>
> .
>

2021-02-16 09:46 UTC, freebelion commented
İptal edin o zaman; faydalı bir şey yapın da onu eklerim.

16 Şub 2021 Sal 12:43 tarihinde yceomer <notifications@github.com> şunu
yazdı:

> Hocam sadece arkadaşların anlaması için toolbox kullanarak bir buton
> ekledim. İşlevi yok sadece görüntü :|
>
> 16 Şub 2021 Sal 12:39 tarihinde Hürol Aslan <notifications@github.com>
> şunu
> yazdı:
>
> > *@freebelion* requested changes on this pull request.
> >
> > Ne işe yarayacağını anlamadığım düğmeye bari anlamlı bir ad koysaydınız
> :-<
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/freebelion/BTS206-2021/pull/1#pullrequestreview-591043791
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ANAPDLOW6CNEVGTOTAWXZIDS7I4MRANCNFSM4XVJ3MSA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/freebelion/BTS206-2021/pull/1#issuecomment-779713358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGBRPEB3B5XFM2VYELU6HCDS7I43HANCNFSM4XVJ3MSA>
> .
>

2021-02-16 13:02 UTC, yceomer reviewed
Butonlar eklendi, butonların işlevleri eklendi. Fakat, sayıları yazmadan 4 işlem butonlarına bastığımızda patlıyor. Çözümü bulabilen geliştirebilir.

2021-02-18 11:30 UTC, yceomer commented
Hocam derste yarım kalan projeyi tarafınızla paylaştım :) 💯

2021-02-22 12:30 UTC, freebelion approved these changes
Okey, sanırım.

2021-02-22 12:32 UTC, merged